name: kiwi_sdr
description: "A new Flutter package for working with KiwiSDR Software Defined Radios."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

